name: Update Status

on:
  repository_dispatch:
    types: [status_update]

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update status.txt
        run: |
          echo "${{ github.event.client_payload.status }}" > status.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "Status Bot"
          git config --global user.email "status-bot@github.com"
          git add status.txt
          git commit -m "Status updated via Discord to ${{ github.event.client_payload.status }}" || exit 0
          git push
